##### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
import numpy as np
list_ = ['1','2','3','4','5' ]
array_list = np.array(object = list_)

In [11]:
print(array_list.dtype)

<U1


In [13]:
print(type(list_))

<class 'list'>


The data type of array_list is u1. U1 is the data type that represents an unsigned integer of 1 byte.The u stands for unsigned and 1 stands for 1 byte. This means it stores a value thtat can be stored in a u1 variable is form 0 to 255.

The data type is list_ is list.

##### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [14]:
for i in list_:
    print(type(i))
    
    

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [15]:
for j in array_list:
    print(type(j))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


##### Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int) Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [19]:
list_ = ['1','2','3','4','5' ]
array_list_num = np.array(object = list_,dtype = int)

In [20]:
array_list_num

array([1, 2, 3, 4, 5])

In [21]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [22]:
for j in array_list_num:
    print(type(j))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

##### Q4. Write a code to find the following characteristics of variable, num_array:
##### (i) shape 
##### (ii) size

In [23]:
num_list = [[1,2,3],[4,5,6]]
num_array = np.array(num_list)

In [25]:
num_array


array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
num_array.shape #gives the number of elements along each dimension of the array

(2, 3)

In [28]:
num_array.size #shows the total numbers of elements present in the array 

6

##### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [31]:
array = np.zeros((3,3))

In [32]:
array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

##### Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [37]:
array2 = np.eye(5)

In [38]:
array2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])